import Link from 'next/link'
import { Mic } from 'lucide-react'

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      <nav className="border-b border-gray-100 px-6 py-4">
        <div className="max-w-4xl mx-auto flex items-center gap-2">
          <Link href="/" className="flex items-center gap-2">
            <div className="w-7 h-7 bg-blue-600 rounded-lg flex items-center justify-center">
              <Mic className="w-3.5 h-3.5 text-white" />
            </div>
            <span className="font-bold text-gray-900">InterviewAI</span>
          </Link>
        </div>
      </nav>
      <main className="max-w-3xl mx-auto px-6 py-12">
        <h1 className="text-3xl font-bold text-gray-900 mb-2">Terms of Service</h1>
        <p className="text-gray-500 mb-8">Last updated: May 25, 2026</p>

        <div className="prose prose-gray max-w-none space-y-6 text-gray-700">
          <section>
            <h2 className="text-xl font-semibold text-gray-900">1. Acceptance of Terms</h2>
            <p>By using InterviewAI, you agree to these terms. InterviewAI is an AI-powered mock interview platform for educational and practice purposes only.</p>
          </section>
          <section>
            <h2 className="text-xl font-semibold text-gray-900">2. Use of Service</h2>
            <p>InterviewAI is for personal interview preparation only. You may not use the service to collect data, reverse-engineer AI models, or resell access. Each account is for individual use.</p>
          </section>
          <section>
            <h2 className="text-xl font-semibold text-gray-900">3. Payments and Refunds</h2>
            <p>All payments are processed by Razorpay. Credits are consumed when an interview session begins. We do not offer refunds for used credits. Subscriptions can be cancelled at any time; existing credits remain available.</p>
          </section>
          <section>
            <h2 className="text-xl font-semibold text-gray-900">4. Disclaimer</h2>
            <p>InterviewAI is a practice tool. We do not guarantee interview success or job placement. AI feedback is generated by large language models and should be treated as guidance, not definitive assessment.</p>
          </section>
          <section>
            <h2 className="text-xl font-semibold text-gray-900">5. Contact</h2>
            <p>For support, email us at support@interviewai.in</p>
          </section>
        </div>
      </main>
    </div>
  )
}
