import Link from 'next/link'
import { Mic } from 'lucide-react'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service — InterviewAI',
  description: 'Terms and conditions for using the InterviewAI platform.',
}

const LAST_UPDATED = 'June 2025'

const SECTIONS = [
  {
    title: '1. Acceptance of Terms',
    content: (
      <>
        <p>
          By accessing or using InterviewAI at <strong>interviewai.in</strong> (the &quot;Platform&quot;),
          you agree to be bound by these Terms of Service (&quot;Terms&quot;). These Terms form a
          legally binding agreement between you and{' '}
          <strong>[Your Registered Legal Entity Name]</strong> (&quot;InterviewAI&quot;, &quot;we&quot;, &quot;us&quot;,
          or &quot;our&quot;), incorporated under the laws of India.
        </p>
        <p className="mt-2">
          If you do not agree to these Terms, do not use the Platform. We reserve the right to
          update these Terms at any time with 14 days&apos; notice. Continued use after the effective
          date constitutes acceptance.
        </p>
      </>
    ),
  },
  {
    title: '2. Eligibility',
    content: (
      <>
        <p>
          You must be at least <strong>18 years of age</strong> to use the Platform. By creating
          an account, you represent and warrant that you are 18 or older and have the legal
          capacity to enter into these Terms. Accounts created on behalf of a minor will be
          terminated and associated data deleted.
        </p>
        <p className="mt-2">
          <strong>Geographic availability:</strong> InterviewAI is currently available
          exclusively to users in <strong>India</strong>. If you are located outside India,
          please discontinue use until we announce availability in your region. We are actively
          working to expand our services globally and will update these Terms accordingly.
        </p>
      </>
    ),
  },
  {
    title: '3. Description of Service',
    content: (
      <>
        <p>
          InterviewAI provides an AI-powered mock interview platform that allows users to
          practise job interviews through voice-based conversations with an AI interviewer,
          receive scored feedback reports, and track improvement over time. The Platform is
          provided for practice and educational purposes only.
        </p>
        <p className="mt-2">
          <strong>InterviewAI is not a recruitment agency</strong> and does not guarantee
          employment outcomes. Interview questions and feedback are generated by AI models and
          are provided &ldquo;as is&rdquo; without warranty as to their accuracy, completeness, or
          suitability for any specific employer.
        </p>
      </>
    ),
  },
  {
    title: '4. User Account',
    content: (
      <ul className="list-disc pl-5 space-y-2">
        <li>You may create one account per Google identity. Creating multiple accounts to claim free credits is prohibited and may result in permanent suspension of all associated accounts.</li>
        <li>You are responsible for all activity that occurs under your account.</li>
        <li>Notify us immediately at <a href="mailto:support@interviewai.in" className="text-blue-600 hover:underline">support@interviewai.in</a> if you suspect unauthorised access.</li>
        <li>We reserve the right to suspend or terminate accounts that violate these Terms.</li>
      </ul>
    ),
  },
  {
    title: '5. Credits and Payments',
    content: (
      <ul className="list-disc pl-5 space-y-2">
        <li><strong>Free credit:</strong> Each new account receives 1 free interview session credit on signup.</li>
        <li><strong>Paid credits:</strong> Additional credits are purchased as one-time packs via Razorpay (Single, Starter, or Serious Prep). All prices are in Indian Rupees (INR) and inclusive of applicable taxes.</li>
        <li><strong>Credits never expire</strong> and are non-transferable. Credits are non-refundable once an interview session has been started and questions have been generated.</li>
        <li><strong>Refund policy:</strong> If a session fails due to a technical error on our end before any questions are asked, we will restore your credit. Contact <a href="mailto:support@interviewai.in" className="text-blue-600 hover:underline">support@interviewai.in</a> within 7 days.</li>
        <li><strong>Credits survive account data deletion.</strong> If you request deletion of your personal data, your remaining credit balance and payment records are retained. Credits you have purchased are not forfeited by a deletion request. Should you return to the Platform, your credits will be intact.</li>
        <li>We reserve the right to change pricing for new purchases with 30 days&apos; advance notice.</li>
      </ul>
    ),
  },
  {
    title: '6. Acceptable Use',
    content: (
      <>
        <p className="mb-2">You agree not to:</p>
        <ul className="list-disc pl-5 space-y-2">
          <li>Use the Platform for any unlawful purpose or in violation of any applicable law.</li>
          <li>Create multiple accounts to claim free credits (account farming).</li>
          <li>Attempt to reverse-engineer, scrape, or extract the AI models, question banks, or proprietary algorithms.</li>
          <li>Use the Platform to train or fine-tune competing AI models.</li>
          <li>Submit content that is defamatory, hateful, sexually explicit, or infringes third-party intellectual property rights.</li>
          <li>Interfere with or disrupt the Platform&apos;s infrastructure, servers, or networks.</li>
          <li>Misrepresent your identity or impersonate any person or entity.</li>
        </ul>
      </>
    ),
  },
  {
    title: '7. Content and Intellectual Property',
    content: (
      <>
        <p>
          <strong>Your content:</strong> You retain ownership of the interview answers, job
          descriptions, and other content you submit (&quot;User Content&quot;). By submitting User
          Content, you grant InterviewAI a limited, worldwide, royalty-free licence to process
          that content solely to provide the service to you (including sending it to our AI
          sub-processors). We do not use your interview transcripts or feedback to train AI models.
        </p>
        <p className="mt-2">
          <strong>Our content:</strong> The Platform — including its design, software, generated
          feedback reports, and all associated intellectual property — is owned by InterviewAI
          and protected under Indian and international copyright and trademark law. You may not
          reproduce, distribute, or create derivative works without prior written consent.
        </p>
      </>
    ),
  },
  {
    title: '8. AI-Generated Content',
    content: (
      <>
        <p>
          Interview questions and feedback reports are generated by large language models
          (currently Anthropic&apos;s Claude). AI-generated content may occasionally be inaccurate,
          incomplete, or not applicable to your specific situation.{' '}
          <strong>We make no warranty that AI feedback accurately reflects how a real interviewer
          would assess you</strong>, and you should not rely solely on InterviewAI feedback when
          preparing for actual interviews.
        </p>
        <p className="mt-2">
          Live audio is transcribed by Deepgram. Transcription accuracy may vary based on
          microphone quality, accent, background noise, and network conditions.
        </p>
      </>
    ),
  },
  {
    title: '9. Privacy',
    content: (
      <p>
        Our collection and use of your personal data is governed by our{' '}
        <Link href="/privacy" className="text-blue-600 hover:underline">Privacy Policy</Link>,
        which is incorporated into these Terms by reference. By using the Platform, you consent
        to the processing of your data as described therein.
      </p>
    ),
  },
  {
    title: '10. Disclaimers',
    content: (
      <p className="uppercase tracking-wide text-xs">
        The platform is provided on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo; basis without warranties
        of any kind, express or implied, including but not limited to warranties of
        merchantability, fitness for a particular purpose, and non-infringement. We do not
        warrant that the platform will be uninterrupted, error-free, or free of harmful
        components.
      </p>
    ),
  },
  {
    title: '11. Limitation of Liability',
    content: (
      <>
        <p className="uppercase tracking-wide text-xs">
          To the maximum extent permitted by applicable law, InterviewAI shall not be liable
          for any indirect, incidental, special, consequential, or punitive damages, including
          loss of profits, data, or goodwill, arising out of or in connection with your use of
          the platform, even if advised of the possibility of such damages.
        </p>
        <p className="mt-2">
          In no event shall our total liability to you exceed the amount you paid to
          InterviewAI in the 3 months immediately preceding the event giving rise to the
          claim, or ₹500, whichever is greater.
        </p>
      </>
    ),
  },
  {
    title: '12. Indemnification',
    content: (
      <p>
        You agree to indemnify and hold harmless InterviewAI and its officers, directors,
        employees, and agents from and against any claims, damages, losses, and expenses
        (including reasonable legal fees) arising out of your use of the Platform, your User
        Content, or your violation of these Terms.
      </p>
    ),
  },
  {
    title: '13. Termination',
    content: (
      <>
        <p>
          You may delete your personal data at any time from your{' '}
          <Link href="/account" className="text-blue-600 hover:underline">Account Settings</Link>{' '}
          page. Deletion removes your name, email, interview history, transcripts, and feedback
          reports. Your credit balance, active subscription, and payment records are{' '}
          <strong>not</strong> deleted — they are retained so you do not lose what you paid for
          and can return to the Platform at any time with your credits intact.
        </p>
        <p className="mt-2">
          We may suspend or terminate your access if you breach these Terms or engage in
          fraudulent activity (including creating multiple accounts to claim free credits).
          Upon such termination, unused credits are forfeited and no refund is issued.
        </p>
      </>
    ),
  },
  {
    title: '14. Governing Law and Dispute Resolution',
    content: (
      <>
        <p>
          These Terms are governed by and construed in accordance with the laws of India. Any
          disputes arising out of or relating to these Terms shall first be attempted to be
          resolved through good-faith negotiation. If unresolved within 30 days, disputes shall
          be submitted to binding arbitration in accordance with the Arbitration and Conciliation
          Act, 1996, with the seat of arbitration in <strong>Mumbai, Maharashtra</strong>. The
          language of arbitration shall be English.
        </p>
        <p className="mt-2">
          Nothing in this clause prevents either party from seeking urgent injunctive relief
          from a court of competent jurisdiction.
        </p>
      </>
    ),
  },
  {
    title: '15. Contact',
    content: (
      <p>
        For questions about these Terms, contact us at:{' '}
        <a href="mailto:legal@interviewai.in" className="text-blue-600 hover:underline">
          legal@interviewai.in
        </a>
      </p>
    ),
  },
]

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gray-50">
      <nav className="bg-white border-b border-gray-200 px-6 py-4">
        <div className="max-w-3xl mx-auto flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <div className="w-7 h-7 bg-blue-600 rounded-lg flex items-center justify-center">
              <Mic className="w-3.5 h-3.5 text-white" />
            </div>
            <span className="font-bold text-gray-900">InterviewAI</span>
          </Link>
          <div className="flex items-center gap-4 text-sm text-gray-500">
            <Link href="/privacy" className="hover:text-gray-900">Privacy Policy</Link>
            <Link href="/dashboard" className="hover:text-gray-900">Dashboard</Link>
          </div>
        </div>
      </nav>

      <main className="max-w-3xl mx-auto px-6 py-12">
        <div className="mb-10">
          <h1 className="text-3xl font-bold text-gray-900 mb-2">Terms of Service</h1>
          <p className="text-sm text-gray-500">Last updated: {LAST_UPDATED}</p>
        </div>

        <div className="space-y-8 text-sm leading-relaxed text-gray-700">
          {SECTIONS.map((s) => (
            <section key={s.title}>
              <h2 className="text-lg font-semibold text-gray-900 mb-3">{s.title}</h2>
              {s.content}
            </section>
          ))}

          <div className="border-t border-gray-200 pt-6 text-xs text-gray-400">
            <p>
              These Terms should be read alongside our{' '}
              <Link href="/privacy" className="text-blue-500 hover:underline">Privacy Policy</Link>.
            </p>
          </div>
        </div>
      </main>
    </div>
  )
}
